<template>
  <table class="table has-text-centered">
    <thead>
      <tr>
        <th>Nombres de séances</th>
        <th>Prix en euros ttc</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>2</td>
        <td>50</td>
      </tr>
      <tr>
        <td>3</td>
        <td>70</td>
      </tr>
      <tr>
        <td>4</td>
        <td>90</td>
      </tr>
      <tr>
        <td>5</td>
        <td>110</td>
      </tr>
      <tr>
        <td>6</td>
        <td>130</td>
      </tr>
      <tr>
        <td>7</td>
        <td>150</td>
      </tr>
      <tr>
        <td>8</td>
        <td>160</td>
      </tr>
      <tr>
        <td>9</td>
        <td>170</td>
      </tr>
      <tr>
        <td>10</td>
        <td>180</td>
      </tr>
    </tbody>
  </table>
</template>
